# serverless.yml
service: kpo-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  kpoUser:
    handler: user.handler
    environment:
      RDS_DATABASE: KAPPO
      RDS_HOSTNAME: localhost
      RDS_USERNAME: kpouser
      RDS_PASSWORD: Kpopass2019
      RDS_PORT: 3306
    events:
      - http:
          path: user
          method: get
      - http:
          path: user/{id}
          method: get
      - http:
          path: user
          method: post
      - http:
          path: user/{id}
          method: put
      - http:
          path: user/{id}
          method: delete
  kpoTrip:
    handler: trip.handler
    environment:
      RDS_DATABASE: KAPPO
      RDS_HOSTNAME: localhost
      RDS_USERNAME: kpouser
      RDS_PASSWORD: Kpopass2019
      RDS_PORT: 3306
    events:
      - http:
          path: trip
          method: get
      - http:
          path: trip
          method: post            
      - http:
          path: trip/{id}
          method: put
      - http:
          path: trip/{id}
          method: delete
      - http:
          path: trip/{id}/{id_user}
          method: get
plugins:
  - serverless-offline