# serverless.yml
service: kpo-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  kpoFunc:
    handler: user.handler
    environment:
      RDS_DATABASE: KAPPO
      RDS_HOSTNAME: localhost
      RDS_USERNAME: kpouser
      RDS_PASSWORD: Kpopass2019
      RDS_PORT: 3306
    events:
      - http:
          path: user
          method: get
      - http:
          path: user/{id}
          method: get
      - http:
          path: user
          method: post
      - http:
          path: user/{id}
          method: put
      - http:
          path: user/{id}
          method: delete

plugins:
  - serverless-offline